spring:
  application:
    name: spring-cloud-sleuth-client
  cloud:
    consul:
      discovery:
        register-health-check: false

server:
  port: 10000


management:
  health:
    refresh:
      enabled: false
