spring:
  application:
    name: micrometer-trace-client
  cloud:
    consul:
      discovery:
        register-health-check: false

server:
  port: 10010


management:
  health:
    refresh:
      enabled: false
